name: Node CI

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'express/**/*.ts'
      - 'express-middlewares/**/*.ts'
      - 'mongoose/**/*.ts'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        redis-version: [5]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis ${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install and test
        run: |
          yarn install
          yarn test
        env:
          CI: true
